spring.application.name=DumbleAuthentication
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/dumble_project
spring.datasource.username=postgres
spring.datasource.password=${DATABASEPASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=dGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgZm9yIGp3dCB0b2tlbiBnZW5lcmF0aW9u
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# Google OAuth
google.client-id=${GOOGLE_CLIENT_ID}